version: "2"

services:
    interlock:
        image: ehazlett/interlock:master
        command: run -c /etc/interlock/config.toml
        ports:
            - 80
        volumes:
            - ./config.toml:/etc/interlock/config.toml
            - /var/run/docker.sock:/var/run/docker.sock

    haproxy:
        image: haproxy:latest
        ports:
            - 80:80
        labels:
            - "interlock.ext.name=haproxy"
        links:
            - interlock:interlock
        depends_on:
            - interlock